name: CICD
on:
 workflow_dispatch: 
 
jobs:
   code:
     runs-on: ubuntu-latest
     steps:
       - name: clone the code
         run: echo "cloning the code" # git clone URL
   build:
     runs-on: ubuntu-24.04-arm
     steps:
       - name: Build using docker
         run: echo "Building using docker" # docker build -t appname .
   test:
     runs-on: ubuntu-latest
     steps:
       - name: Running test cases
         run: echo "Testing the app" #run commands recomended by tester 
   deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Deploying on the machine
         run: echo "Deploying the code"
