# what is the goal of your workflow
# Goal: whenever someone changes the python code, 
# the linter will check if the syntax, format, intendation(Linting) is correct or not
name: Auto Linter
on:
  push:
    paths: "*.py"
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/Clone the code
        uses: actions/checkout@v4
        
# this step to install python 
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
 
# this step will install linter tool to check phython code
      - name: Install Linter
        run: pip install ruff

      - name: Check thefiles for linter
        run: ruff check .
